apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  type: ClusterIP #internal communications within the cluster only
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 80 