apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment 
spec:
  selector:
    matchLabels:
      app: users
  replicas: 1
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: pmkays/kub-demo-users

